version: 2

sources: 
  - name: raw_data
    database: sales_db 
    schema: raw
    tables: 
      - name: orders
      - name: order_items
      - name: products 
      - name: customers

models: 
  - name: stg_customer
    description: ""
    columns:
      - name: customer_id
        description: ""
        data_type: numeric
        data_tests:
          - unique: 
             config:
              severity: error
          - not_null:
              config:
                severity: error

      - name: cust_name
        description: ""
        data_type: text
      
      - name: cust_email
        description: ""
        data_type: text
        data_tests: 
          - unique:
              config: 
                severity: error
      
      - name: country
        description: ""
        data_type: text

  - name: stg_order_items
    description: ""
    columns:
      - name : ordItem_id 
        description: ""
        data_type: numeric
        data_tests: 
          - unique: 
              config:
                severity: warn
          - not_null: 
              config: 
                severity: warn
      
      - name: order_id
        description: ""
        data_type: numeric
      
      - name: product_id
        description: ""
        data_type: numeric       

      - name: quantity
        description: ""
        data_type: numeric       

      - name: unit_price
        description: ""
        data_type: numeric  
    
      - name: total_amount
        description: ""
        data_type: numeric            
  
  - name: stg_orders
    description: ""
    columns:
      - name: order_id
        description: ""
        data_type: numeric
        data_tests:
          - unique:
              config:
                severity: error
          - not_null:
              config:
                severity: error

      - name: customer_id
        description: ""
        data_type: numeric
        data_tests: 
          - not_null:
             config: 
              severity: warn
      
      - name: order_date
        description: ""
        data_type: date 
      
      - name: total_amount
        description: ""
        data_type: numeric
  
  - name: stg_products 
    description: ""
    columns: 
      - name: product_id
        description: ""
        data_type: numeric
        data_tests: 
          - unique: 
              config: 
                severity: error
          - not_null:
              config:
                severity: error
      
      - name: product_name
        description: ""
        data_type: text 
      
      - name: category
        description: ""
        data_type: text 
      
      - name: price
        description: ""
        data_type: numeric